### PR TITLE
Bug fixes and Refactoring

### PR DESCRIPTION
**Pull request by soffensive**
Several bug fixes and code clean up
    
    Fixes include:
    - Do not rely on content-length sent by the server
    - isProtected() always yielded "True" due to missing parameter to call of isInfiniteLoopProtected
    - stripAuthorizationCharacteristics() used only LF instead of CRLF. This
    caused the unauthenticated sending always to fail
    - compareResponses contained a typo, which also caused it to fail

### CODE REVIEW

**Comment by luh2** [comment]
Hi soffensive,

Thanks for your pull request. To ease accepting pull requests, if you send a pull request, please make sure it addresses only one change and not multiple ones at the same time. It makes reading the pull requests easier, and thus quicker to accept.

I noticed, you also supplied some changes for organizational things like Changelog and versions. That is unecessary. I'll keep managing myself. I'd rather you remove those from your pull request.

Is there a reason you changed line 176-178?

I am fine with renaming all the mis-named authorization to authentication. Line 197, the description should stay though. Cookies and basic auth headers are called ambient authority information.

Why did you change testing the content-length method? Will Jython complain about requesting an empty body?

Line 256, what is your intention with the comment? Is it a  "TODO: rerequest, because it has been cached" or just an explanation of what the line is doing? If it's the latter, I think we don't need the comment.

Thanks again. If you could change those things as said above, I'll be happy to accept. Those generally look like good changes!

**Comment by luh2** [comment]
As soon as the commits are free of organizational stuff (versions, etc) and each commit does one thing, I'll pull it asap.

**Comment by soffensive** [comment]
- Lines 176-178: Overall, I consider the use of any/all harmful unless absolutely necessary, since it can lead to unwanted behaviour and bugs (e.g., line 148, where any() always returned True although none of the single members yielded True). 
So I would suggest to replace calls to these functions with standard logical and/or operators
- hasBody(): The reason for this change was due to the behaviour of the Google Gruyere app, which is based on Python. Strangely, server responses did not consistently contain Content-Length headers, which caused the function hasBody() to return False, even though there was a body present. So this is just a way of being more lenient towards strange web servers.
- Line 256: This intention should improve the readability, since I do not know every HTTP response status code by heart (presumably, neither does everyone else)

**Comment by luh2** [comment]
- I was not aware, a response could be returned without Content-Length. Sounds like a legit change to me.
- I am not convinced it needs that comment, but it doesn't change anything critical, so sure. Let's keep it. 
`# Only compare, if the response wasn't cached`
- I think the all/anys provide better readability. While you have a point, that in this case, it made me overlook a bug, I think I'd prefer to stick with it for now.

**Comment by luh2** [comment]
My main concern was that this expression with ands does not use lazy evaluation (short-circuit after realizing, some of those are already false), so yes, - let's change those three lines to ands instead of all.

**Comment by luh2** [comment]
I'll close this one, as all your changes were in the other pull request. Thanks again.

**Pull request closed without merging**
